# Generated by Django 2.2.17 on 2021-01-13 04:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='title for this note', max_length=32)),
                ('scope', models.CharField(choices=[('public', 'public'), ('group', 'group'), ('private', 'private')], default='public', help_text='sets access to this note', max_length=8)),
                ('permissions', models.CharField(choices=[('read', 'read'), ('read, edit', 'read, edit'), ('read, edit, delete', 'read, edit, delete'), ('read, delete', 'read, delete')], default='read', help_text='operations allowed on this note', max_length=32)),
                ('content', models.TextField(help_text='the actual content of this note')),
                ('object_id', models.PositiveIntegerField()),
                ('object_repr', models.CharField(blank=True, help_text='string representation of an object instance', max_length=128, null=True)),
                ('author', models.ForeignKey(blank=True, help_text='user who created this note', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('groups', models.ManyToManyField(blank=True, help_text='if group scoped, groups who can view this note', to='auth.Group')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
