# Generated by Django 3.2.16 on 2022-12-25 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('modelnotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content_type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='note',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
