# Generated by Django 3.2.16 on 2022-12-25 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('modelnotes', '0002_auto_20221225_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
