# Generated by Django 3.2.16 on 2022-12-25 22:06

from django.db import migrations, models
import modelnotes.models


class Migration(migrations.Migration):

    dependencies = [
        ('modelnotes', '0004_auto_20221225_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='scope',
            field=models.ForeignKey(blank=True, default=modelnotes.models.get_default_scope, help_text='sets access to this note', on_delete=modelnotes.models.get_default_scope, to='modelnotes.scope'),
        ),
    ]
